# [](fg:#3B4252)\
# [](bg:#434C5E fg:#3B4252)\
# [](fg:#434C5E bg:#4C566A)\
# [](fg:#4C566A bg:#86BBD8)\
# [](fg:#86BBD8 bg:#06969A)\
# [](fg:#06969A bg:#33658A)\
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$c\
$python\
$rust\
$docker_context\
[\\$ ](fg:#33658A)\
"""
# $time\
# [ ](fg:#33658A)\
command_timeout = 5000
add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
# style_user = "bold fg:cyan bg:#3B4252"
style_user = "bold fg:cyan"
style_root = "bg:#3B4252"
format = '[$user@]($style)'

[hostname]
style = "bold fg:yellow"
# style = "bold fg:cyan bg:#3B4252"
format = '[$hostname:]($style)'

[directory]
# style = "fg:#86BBD8"
style = "fg:#b2e28a"
format = "[$path]($style)"
truncation_length = 3
truncation_symbol = "…/"

[c]
symbol = " "
# style = "bg:#86BBD8"
format = '[ ($version) ]($style)'

[docker_context]
symbol = " "
# style = "bg:#06969A"
format = '[ $context ]($style) $path'

[python]
# symbol = " "
# style = "bg:#86BBD8"
format = '[ ($version) ]($style)'

[git_branch]
symbol = ""
style = "fg:#8ae2bf"
format = '[ \[$branch]($style)'
# format = '[ \[$symbol$branch ]($style)'

[git_status]
style = "fg:#8ae2bf"
format = '[$all_status$ahead_behind\]]($style)'

[rust]
# symbol = ""
# style = "bg:#86BBD8"
format = '[ ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#33658A"
format = '[ $time\$ ]($style)'
# ~/.config/starship.toml

# [status]
# style = 'bg:blue'
# symbol = ''
# not_found_symbol = ''
# not_executable = ''
# signal_symbol = ''
# format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
# map_symbol = true
# disabled = false
# time_format = "%R" # Hour:Minute Format
# style = "fg:#33658A"
# format = '[ $time\$ ]($style)'
# # ~/.config/starship.toml
#
# # [status]
# # style = 'bg:blue'
# # symbol = ''
# # not_found_symbol = ''
# # not_executable = ''
# # signal_symbol = ''
# # format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
# # map_symbol = true
# # disabled = false
# #
